name: pre-commit

on:
  pull_request:
  push:
    branches: ['**']

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 12
    - uses: pre-commit/action@v3.0.0
